[package]
name = "breccia"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

description = "Append-only blob storage with efficient random access"

[dependencies]
memmap2 = "0.9.5"
thiserror = "2.0.12"

[dev-dependencies]
rand = "0.9.0"
tempfile = "3.19.1"
